name: thuraya
description: "The Thuraya Flutter application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  flutter_svg: ^2.3.0
  http: ^1.6.0
  geolocator: 14.0.3
  maplibre_gl: ^0.27.1
  share_plus: ^13.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/branding/
    - assets/map/
    - assets/images/trending/
    - assets/images/awards/
    - assets/images/restaurant_details/
    - assets/images/home/
    - assets/icons/trending/
    - assets/icons/restaurant_details/
    - assets/icons/wheel/
    - assets/icons/home/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
